export const GET_AUDITS_STARTED = "GET_AUDITS_STARTED";
export const GET_AUDITS_SUCCESS = "GET_AUDITS_SUCCESS";
export const GET_AUDITS_FAILED = "GET_AUDITS_FAILED";

export const GET_AUDIT = "GET_AUDIT";
export const EMPTY_SELECTED_AUDIT = "EMPTY_SELECTED_AUDIT";