export const GET_AUDITS_STARTED = "GET_AUDITS_STARTED";
export const GET_AUDITS_SUCCESS = "GET_AUDITS_SUCCESS";
export const GET_AUDITS_FAILED = "GET_AUDITS_FAILED";

export const GET_AUDIT = "GET_AUDIT";
export const EMPTY_SELECTED_AUDIT = "EMPTY_SELECTED_AUDIT";

export const SHOWSIDEMENU_TRUE = "SHOWSIDEMENU_TRUE";
export const SHOWSIDEMENU_FALSE = "SHOWSIDEMENU_FALSE";

export const SHOW_ADDAUDIT_TRUE = "SHOW_ADDAUDIT_TRUE";
export const SHOW_ADDAUDIT_FALSE = "SHOW_ADDAUDIT_FALSE";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CURRENT_USER = "CURRENT_USER";
export const LOAD_USER = "LOAD_USER";
export const FAIL_USER = "FAIL_USER";


export const GET_ANOMALIES_STARTED = "GET_ANOMALIES_STARTED";
export const GET_ANOMALIES_SUCCESS = "GET_ANOMALIES_SUCCESS";
export const GET_ANOMALIES_FAILED = "GET_ANOMALIES_FAILED";

export const GET_ANOMALIE = "GET_ANOMALIE";
export const EMPTY_SELECTED_ANOMALIE = "EMPTY_SELECTED_ANOMALIE";

export const SHOW_ADDANOMALIE_TRUE = "SHOW_ADDANOMALIE_TRUE";
export const SHOW_ADDANOMALIE_FALSE = "SHOW_ADDANOMALIE_FALSE";




export const GET_ACTIONCORRECTIVES_STARTED = "GET_ACTIONCORRECTIVES_STARTED";
export const GET_ACTIONCORRECTIVES_SUCCESS = "GET_ACTIONCORRECTIVES_SUCCESS";
export const GET_ACTIONCORRECTIVES_FAILED = "GET_ACTIONCORRECTIVES_FAILED";

export const GET_ACTIONCORRECTIVE = "GET_ACTIONCORRECTIVE";
export const EMPTY_SELECTED_ACTIONCORRECTIVE = "EMPTY_SELECTED_ACTIONCORRECTIVE";

export const SHOW_ADDACTIONCORRECTIVE_TRUE = "SHOW_ADDACTIONCORRECTIVE_TRUE";
export const SHOW_ADDACTIONCORRECTIVE_FALSE = "SHOW_ADDACTIONCORRECTIVE_FALSE";


export const GET_USERS_STARTED = "GET_USERS_STARTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";